<?php

/**
 * @file
 * Implements any hooks for GSB Panels Pages.
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function gsb_panels_pages_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
  if ($module == "panels_mini" && $api == "panels_default") {
    return array("version" => "1");
  }
}
